### ISSUE TITLE
motion control design

### ISSUE THREAD

**Issue by chenzed** [tdehaeze/stewart-simscape#1]
Hallo I'm a student from China. I'm also studing the Stewart Platoform.
I learned so much from your project, but I have a question about the Motion contron desige.
I want to know what theory did you desige the controller. I saw you write the controller directly from the Plant analysis . I don't know why KL need a pure integrator and a low pass filter. I also don't know why the wc frequency is 30Hz.
I'm looking forward to hearing from you.

**Comment by tdehaeze** [comment]
Hi @chenzed!

Good to hear that you could learn about Stewart Platforms from this project.

On the file about Tracking Control, I just wanted to show the differences of designing the controller in the task's space or in the leg's space.

I choose to try a diagonal controller with pure integrator and a low pass filter just because it is a very simple architecture.
The integral action permits to have no tracking error at DC, and the low pass filter after the crossover permits to increase the gain margin (problematic due to resonances with small damping at high frequency).
This controller is clearly not optimal nor really robust and should probably not be use in practice as is.

I advise you to read some papers on the control of such Stewart platforms.
I started to gather all papers/books/phd thesis about Stewart platforms on this page: https://tdehaeze.github.io/stewart-simscape/bibliography.html

As a starting point, the book "Taghirad, Parallel robots : mechanics and control, CRC Press (2013)" is really nice.
Most of my results presented here are based on this book.

Then, the control that you will want to use clearly depends both on the Stewart platform configuration that you have (sensors, actuators, stiffness, ...) and application (vibration isolation, tracking control, force control, ...).

Have a great day

**Comment by chenzed** [comment]
I'm so grad to hear from you!you are a good guy. I will try some different ways on motion control. I've already bought the book you mentioned. That book has inspired me a lot, too. Really, really thank you very much，Have a good time-------- 原始邮件 --------发件人： Thomas Dehaeze <notifications@github.com>日期： 2020年4月14日周二 下午3:37收件人： tdehaeze/stewart-simscape <stewart-simscape@noreply.github.com>抄送： chenzed <chenzedong@buaa.edu.cn>, Mention <mention@noreply.github.com>主    题： Re: [tdehaeze/stewart-simscape] motion control design (#1)
Hi @chenzed!
Good to hear that you could learn about Stewart Platforms from this project.
On the file about Tracking Control, I just wanted to show the differences of designing the controller in the task's space or in the leg's space.
I choose to try a diagonal controller with pure integrator and a low pass filter just because it is a very simple architecture.
The integral action permits to have no tracking error at DC, and the low pass filter after the crossover permits to increase the gain margin (problematic due to resonances with small damping at high frequency).
This controller is clearly not optimal nor really robust and should probably not be use in practice as is.
I advise you to read some papers on the control of such Stewart platforms.
I started to gather all papers/books/phd thesis about Stewart platforms on this page: https://tdehaeze.github.io/stewart-simscape/bibliography.html
As a starting point, the book "Taghirad, Parallel robots : mechanics and control, CRC Press (2013)" is really nice.
Most of my results presented here are based on this book.
Then, the control that you will want to use clearly depends both on the Stewart platform configuration that you have (sensors, actuators, stiffness, ...) and application (vibration isolation, tracking control, force control, ...).
Have a great day
